name: Release build

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: "Test version"
        required: true
        default: "0.0.1"
jobs:
  build:
    runs-on: windows-2022

    env:
      MCDUServerFileName: "cj4-mcdu-server.exe"
      OutputFolder: "release"

    defaults:
      run:
        working-directory: src/app
        shell: pwsh

    steps:
      - uses: actions/checkout@v3

      # Get the version of the GitHub release for use later. This is only valid
      # when run in a release context
      - name: Get GitHub release version
        id: get_github_version
        uses: battila7/get-version-action@v2
        if: startsWith(github.ref, 'refs/tags/')
      - name: Store GitHub release version
        id: save_github_version
        run: echo "version=${{ steps.get_github_version.outputs.version-without-v }}" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/')

      # Get the version from the workflow input. This is only valid
      # when run manually as a workflow.
      - name: Store workflow version
        id: save_workflow_version
        run: echo "version=${{ github.event.inputs.version }}" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/') == false

      - name: Set package.json version
        id: package_version
        uses: KageKirin/set-node-package-version@v0
        with:
          version: ${{ env.version }}

      - name: Use Node.js 14.x
        id: install_node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: "npm"

      - name: Setup node dependencies
        id: install_dependencies
        run: npm ci

      - name: Build client
        id: build_client
        run: npm run build:client

      - name: Build server
        id: build_server
        run: npm run build:mcdu-server

      - name: Build release folder contents
        id: build_release_folder
        run: |
          Move-Item "../../build/MCDU SERVER/${{ env.MCDUServerFileName }}.exe" "../../build/MCDU SERVER/${{ env.MCDUServerFileName }}-${{ env.version }}"
          Copy-Item ../../readme.md ../../build
          Copy-Item ../../version ../../build

      # Install the zip command line tool to package up the output
      - name: Install zip
        id: install_zip
        uses: montudor/action-zip@v1

      - name: Zip output
        id: zip_output
        run: zip -qq -r "../../${{ env.OutputFolder }}/${{ env.MCDUServerFileName }}-${{ env.version }}.zip" *.*
        working-directory: "../../build"

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release_files
          path: ../../${{ env.OutputFolder }}/**

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: "../../release/${{ env.MCDUServerFileName }}-${{ env.version}}.zip"
